api_platform:
    title: Hello API Platform
    version: 1.0.0 # disables when APP_DEBUG is false
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
