services:
  database:
    image: 'mysql:9'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybank-api-database
    ports:
      - '3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'

  database_test:
    image: 'mysql:9'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybank-api-database_test
    ports:
      - '3307:3306'
    volumes:
      - 'mysql_data_test:/var/lib/mysql'

  backend:
    build: .
    ports:
      - '8082:80'
    depends_on:
      - database
      - database_test

volumes:
  mysql_data:
  mysql_data_test:
